autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.2

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.8.17
    remappings:
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.7.2/contracts"
      - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.2/contracts"
